# Generated by Django 5.2.3 on 2025-07-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('rating', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
