# Generated by Django 5.2.3 on 2025-07-30 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=20)),
                ('appointment_date', models.DateTimeField(default=None)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electitions.electrition')),
            ],
        ),
    ]
