# Generated by Django 5.2.3 on 2025-07-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electitions', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='provider_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(default='electrition', max_length=100),
        ),
    ]
