# Generated by Django 5.2.3 on 2025-07-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electitions', '0003_appointment_provider_id_appointment_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service_type',
        ),
    ]
