# Generated by Django 5.2.3 on 2025-07-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electitions', '0004_remove_appointment_provider_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='plumber',
            new_name='electrition',
        ),
    ]
