# Generated by Django 5.2.3 on 2025-07-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electitions', '0005_rename_plumber_appointment_electrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
