# Generated by Django 5.2.3 on 2025-07-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(default=None),
        ),
    ]
