# Generated by Django 5.2.3 on 2025-07-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0004_alter_appointment_plumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='plumber',
        ),
    ]
