# Generated by Django 5.2.3 on 2025-07-12 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0005_remove_appointment_plumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='plumber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plumbing.plumber'),
            preserve_default=False,
        ),
    ]
